export const data = [
  {
    id: 5.6,
    projectName: "Password Generator",
    github: "https://github.com/lucho20091/password-generator",
    website: "https://passwordgenerator-lmms.netlify.app/",
    technologies: ["HTML"],
  },
  {
    id: 6,
    projectName: "We are the champions",
    github: "https://github.com/lucho20091/We-are-the-Champions",
    website: "https://we-are-the-champions-lmms.netlify.app/",
    technologies: ["Firebase"],
    stars: 2,
  },
  {
    id: 20.5,
    projectName: "Moviewatchlist",
    github: "https://github.com/lucho20091/movie-watchlist",
    website: "https://moviewatchlist-v.netlify.app/",
    technologies: ["HTML"],
    stars: 3,
  },
  {
    id: 26,
    projectName: "React Journey",
    github: "https://github.com/lucho20091/journey-react",
    website: "https://traveljournal-v.netlify.app/",
    technologies: ["React"],
  },
  {
    id: 29,
    projectName: "Sprivaten ",
    github: "https://github.com/lucho20091/Sprivaten",
    website: "https://sprivaten-css.netlify.app/",
    technologies: ["HTML"],
    responsive: true,
    stars: 2,
  },
  {
    id: 30,
    projectName: "Portfolio Mockup ",
    github: "https://github.com/lucho20091/portfolio-mockup",
    website: "https://portfolio-mockup-lmms.netlify.app/",
    technologies: ["HTML"],
    responsive: true,
    stars: 2,
  },
  {
    id: 32,
    projectName: "Firebase app Moody ",
    github: "https://github.com/lucho20091/Firebase-app",
    website: "https://Firebaseapp-lmms.netlify.app/",
    technologies: ["Firebase"],
    stars: 4,
  },

  {
    id: 35,
    projectName: "Weather App",
    github: "https://github.com/lucho20091/weather-app-06-09",
    website: "https://weather-app-0609.netlify.app/",
    technologies: ["HTML"],
    stars: 2,
  },
  {
    id: 36,
    projectName: "Firebase Cart List ",
    github:
      "https://github.com/lucho20091/Mobile-App-Old-from-Making-Websites-Interactive",
    website: "https://mobile-app-old-making-interactive-web.netlify.app/",
    technologies: ["Firebase"],
    stars: 2,
  },
  {
    id: 37,
    projectName: "Funiro Ecommerce ",
    github: "https://github.com/lucho20091/ecommerce-august-v2",
    website: "https://ecommerceweb-v.netlify.app/",
    technologies: ["HTML"],
    stars: 3,
  },
  {
    id: 40,
    projectName: "Shopcart ",
    github: "https://github.com/lucho20091/codevibing-something-v2",
    website: "https://majestic-marzipan-38530c.netlify.app/",
    technologies: ["React"],
    responsive: true,
    stars: 3,
  },
  {
    id: 41,
    projectName: "Reactgram ",
    github: "https://github.com/lucho20091/instagram-clone-react",
    website: "https://reactgram-lmms.netlify.app/",
    technologies: ["React", "Firebase"],
    stars: 4,
  },
  {
    id: 42,
    projectName: "Reactflix ",
    github: "https://github.com/lucho20091/netflix-clone",
    website: "https://netfiixclone-react.netlify.app/",
    technologies: ["React", "Firebase"],
    stars: 4,
  },
  {
    id: 44,
    projectName: "LandingPro ",
    github: "https://github.com/lucho20091/leadflow",
    website: "https://ladingpro.netlify.app/",
    technologies: ["React"],
    responsive: true,
    stars: 3,
  },
  {
    id: 48,
    projectName: "Blogs 2",
    github: "https://github.com/lucho20091/blog-website-w3",
    website: "",
    technologies: ["Express", "MongoDB"],
    stars: 4,
  },

  {
    id: 50,
    projectName: "Rate limiting Express ",
    github: "https://github.com/lucho20091/rate-limit",
    website: "",
    technologies: ["Express"],
    stars: 3,
  },

  {
    id: 55,
    projectName: "Letterbox - MERN",
    github: "https://github.com/lucho20091/letterbox-test-3",
    website: "https://movies.lucho.uk/",
    technologies: ["Express", "React", "MongoDB"],
    responsive: true,
    stars: 4,
  },

  {
    id: 57,
    projectName: "Next Letterbox ",
    github: "https://github.com/lucho20091/letterbox-next",
    website: "https://www.lettermovies.lucho.uk/",
    technologies: ["Next", "MongoDB"],
    responsive: true,
    stars: 4,
  },
  {
    id: 58,
    projectName: "Next Movies ",
    github: "https://github.com/lucho20091/watchmovies",
    website: "https://moviesfree.lucho.uk/",
    technologies: ["Next"],
    responsive: true,
    stars: 4,
  },
  {
    id: 59,
    projectName: "DigitalLaunchpad HTML ",
    github: "https://github.com/lucho20091/html-tailwind",
    website: "https://digitallaunchpad.lucho.uk/",
    technologies: ["HTML"],
    responsive: true,
    stars: 2,
  },
  {
    id: 60,
    projectName: "Next Job Tracker",
    github: "https://github.com/lucho20091/job-tracker",
    website: "https://jobtracker-lucho.vercel.app/",
    technologies: ["Next"],
    responsive: true,
    stars: 4,
  },
  {
    id: 61,
    projectName: "Next SMedia",
    github: "https://github.com/lucho20091/next-smedia",
    website: "https://smedia.lucho.uk/",
    technologies: ["Next"],
    responsive: true,
    stars: 4,
  },
  {
    id: 62,
    projectName: "Next Ecomm",
    github: "https://github.com/lucho20091/next-test-ec",
    website: "",
    technologies: ["Next"],
    responsive: true,
    stars: 4,
  },
];

